require:
  # - rubocop-rspec
  - rubocop-rails
  # - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
    - 'db/seeders/*'
    - '.git/**/*'

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - 'app/models/booking.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
    - 'app/models/ability.rb'

Style/MixinUsage:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*'
    - 'config/initializers/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - 'to'
    - 'at'

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
