AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
    - 'db/seeders/*'
    - '.git/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Style/MixinUsage:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*'
    - 'config/initializers/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - 'to'
    - 'at'
