version: '3.7'
services:

  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - app_vendor:/app/vendor
      - app_cache:/app/.cache
    ports:
      - '3000:3000'
    entrypoint: [".docker/entrypoints/app.sh"]
    command: ["bin/rails", "s", "-b", "0.0.0.0", "-p", "3000"]
    environment:
      APP_HOST: ${APP_HOST:-heimv.localhost:3000}
      DATABASE_URL: postgresql://postgres:postgres@db/heimverwaltung_development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpack
      MAILER_URL: "smtp://mail?from=no-reply@heimverwaltung.localhost"
    depends_on:
      - db
      - webpack
      - mail
    tty: true
    stdin_open: true
    # user: "${UID:-1000}:${GID:-1000}"

  db:
    image: postgres:11-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: heimverwaltung_test
      POSTGRES_PASSWORD: postgres

  webpack:
    build:
      context: .
      target: development
    entrypoint: [".docker/entrypoints/webpack.sh"]
    command: ["bin/webpack-dev-server"]
    volumes:
      - .:/app
      - webpack_node_modules:/app/node_modules
      - webpack_vendor:/app/vendor
      - webpack_cache:/app/.cache
      # - ../vue-occupancies-calendar/:/vue-occupancies-calendar
    environment:
      NODE_ENV: development
      NODE_PATH: /app/node_modules
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - '3035:3035'
    # user: "${UID:-1000}:${GID:-1000}"

  mail:
    image: tophfr/mailcatcher
    ports:
      - '1080:80'
      - '1025:25'

  memcached:
    image: memcached:1.5-alpine
    command: [ memcached, -l, '0.0.0.0', -p, '11211' ]

  test:
    build:
      context: .
      target: development
    entrypoint: [".docker/entrypoints/app.sh"]
    command: ["bin/check"]
    volumes:
      - .:/app
      - test_node_modules:/app/node_modules
      - test_vendor:/app/vendor
      - test_cache:/app/.cache
    environment:
      E2E_HOST: 'http://production:3002'
      # E2E_HOST: 'http://test:3002'
      # RAILS_PORT: 3002
      DATABASE_URL: postgresql://postgres:postgres@db/heimverwaltung_test
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 'true'
      RAILS_ENV: test
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
      MAILER_URL: "test://localhost?from=no-reply@heimverwaltung.localhost"
      RUBYOPT: '-W:no-deprecated -W:no-experimental'
    depends_on:
      - db
      - selenium
      - webpack
      - production
    # user: "${UID:-1000}:${GID:-1000}"
    networks:
      default:
      selenium:

  production:
    build: .
    image: heimv:latest
    ports:
      - '3002:3002'
    volumes:
      - /app/.cache
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/heimverwaltung_test
      MAILER_URL: "smtp://mail?from=no-reply@heimverwaltung.localhost"
      SECRET_KEY_BASE: 'test'
      RAILS_SERVE_STATIC_FILES: 'true'
      PORT: 3002
      LOG_LEVEL: 'debug'
      #MEMCACHE_SERVERS: memcached
      RUBYOPT: '-W:no-deprecated -W:no-experimental'
    depends_on:
      - db
      - mail
      #- memcached
    networks:
      default:
      selenium:

  selenium:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    networks:
      selenium:

networks:
  selenium:

volumes:
  db_data:
  test_node_modules:
  test_vendor:
  test_cache:
  app_node_modules:
  app_vendor:
  app_cache:
  webpack_node_modules:
  webpack_vendor:
  webpack_cache:
