version: '3.5'
services:

  db:
    image: postgres
    volumes:
      - ./tmp/docker/db/data:/var/lib/postgresql/data

  web:
    build: .
    entrypoint: bin/entry
    environment:
      DATABASE_URL: postgresql://postgres@db/
      RAILS_ENV: development
    depends_on:
      - db
