version: '3.5'
services:

  web:
    entrypoint: bin/entry
    command: bin/check
    volumes:
      - .:/app
      - ./tmp/docker/node_modules:/app/node_modules
    environment:
      DATABASE_URL: postgresql://postgres@db/
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 'true'
      RAILS_ENV: test
    depends_on:
      - db
