version: '3.5'
services:

  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: production
    environment:
      DATABASE_URL: postgresql://postgres@db/heimverwaltung_production
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    depends_on:
      - db

volumes:
  db_data:
