version: '3.7'
services:

  app: &app
    build:
      context: .
      target: development
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    entrypoint: [".docker/entrypoints/app.sh"]
    command: ["bin/rails", "s", "-b", "0.0.0.0", "-p", "3000"]
    environment:
      APP_HOST: ${APP_HOST:-heimv.localhost:3000}
      WEBPACKER_DEV_SERVER_HOST: webpack
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 'true'
      RUBYOPT: '-W:no-deprecated -W:no-experimental'
    depends_on:
      - db
      - webpack
      - mail
    tty: true
    stdin_open: true

  db:
    image: postgres:11-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: heimverwaltung_e2e
      POSTGRES_PASSWORD: postgres

  webpack:
    build:
      context: .
      target: development
      args:
        UID: ${UID}
        GID: ${GID}
    entrypoint: [".docker/entrypoints/webpack.sh"]
    command: ["bin/webpack-dev-server"]
    volumes:
      - .:/app
      # - ../vue-occupancies-calendar/:/vue-occupancies-calendar
    environment:
      NODE_ENV: development
      NODE_PATH: /app/node_modules
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - '3035:3035'
    restart: on-failure

  mail:
    image: tophfr/mailcatcher
    ports:
      - '1080:80'
      - '1025:25'

volumes:
  db_data:
