version: '3.5'
services:

  app:
    build:
      context: .
      target: base
    command: bin/rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/app:cached
      - app_node_modules:/app/node_modules
      - app_bundle:/usr/local/bundle/
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres@db/heimverwaltung_development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpack
      WEBPACKER_PRECOMPILE: 'false'
      MAILER_URL: "smtp://mail?from=no-reply@heimverwaltung.localhost"
      MIGRATE_DATABASE: 'true'
    depends_on:
      - db
      - webpack
      - mail
    # tty: true
    # stdin_open: true
    tmpfs:
       - /app/log

  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: heimverwaltung_development

  webpack:
    build:
      context: .
      target: base
    command: bin/webpack-dev-server
    volumes:
      - .:/app:cached
      - webpack_node_modules:/app/node_modules
      - webpack_bundle:/usr/local/bundle/
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - '3035:3035'

  mail:
    image: tophfr/mailcatcher
    ports:
      - '1080:80'
      - '1025:25'

volumes:
  app_bundle:
  app_node_modules:
  webpack_bundle:
  webpack_node_modules:
  db_data:
