version: '3.5'
services:

  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: base
    image: registry.gitlab.com/diegosteiner/heimv
    command: bin/rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
      - app_bundle:/usr/local/bundle/
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres@db/heimverwaltung_development
      # DATABASE_URL: postgresql://postgres@db/heimverwaltung_production
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpack
      BUNDLE_INSTALL: 'true'
      YARN_INSTALL: 'true'
      # WEBPACKER_PRECOMPILE: 'true'
      MAILER_URL: "smtp://mail?from=no-reply@heimverwaltung.localhost"
      MIGRATE_DATABASE: 'true'
      MEMCACHE_SERVERS: memcached
    depends_on:
      - db
      - webpack
      - mail
      - memcached
    tty: true
    stdin_open: true

  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: heimverwaltung_development

  webpack:
    build:
      context: .
      target: base
    command: bin/webpack-dev-server
    entrypoint: ./.docker/entrypoints/webpack.sh
    volumes:
      - .:/app
      - webpack_node_modules:/app/node_modules
      - webpack_bundle:/usr/local/bundle/
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - '3035:3035'

  mail:
    image: tophfr/mailcatcher
    ports:
      - '1080:80'
      - '1025:25'

  memcached:
    image: memcached:1.5-alpine
    command: [ memcached, -l, '0.0.0.0', -p, '11211' ]

  test:
    build:
      context: .
      target: base
    command: bin/check
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - app_bundle:/usr/local/bundle/
    environment:
      APP_HOST: test
      PORT: 3001
      DATABASE_URL: postgresql://postgres@db/heimverwaltung_test
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 'true'
      RAILS_ENV: test
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
      NODE_ENV: production
      WEBPACKER_PRECOMPILE: 'true'
      MAIL_FROM: no-reply@heimverwaltung.localhost
      YARN_INSTALL: 'true'
      BUNDLE_INSTALL: 'true'
    depends_on:
      - db
      - selenium
    networks:
      default:
      selenium:
        aliases:
          - test

  selenium:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    networks:
      selenium:

networks:
  selenium:

volumes:
  app_bundle:
  app_node_modules:
  webpack_bundle:
  webpack_node_modules:
  db_data:
