version: '3.5'
services:

  app:
    entrypoint: bin/entry
    command: bin/rails s -p ${PORT:-3000} -b '0.0.0.0'
    volumes:
      - .:/app
      - ./tmp/docker/node_modules:/app/node_modules
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      DATABASE_URL: postgresql://postgres@db/app_development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpack
      MAILER_URL: "smtp://mail?from=no-reply@heimverwaltung.localhost"
      BUNDLE_PATH: /usr/local/bundle
    depends_on:
      - db
      - webpack
      - mail
    tmpfs:
      #  - /app/tmp
       - /app/log

  webpack:
    build: .
    command: bin/webpack-dev-server
    volumes:
      - .:/app
      - ./tmp/docker/node_modules:/app/node_modules
      # - ../vue-occupancies-calendar:/app/node_modules/vue-occupancies-calendar

    environment:
      RAILS_ENV: development
      NODE_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - '3035:3035'
    # tmpfs: /app/public/packs

  mail:
    image: tophfr/mailcatcher
    ports:
      - '1080:80'
      - '1025:25'
