version: '3.5'
services:

  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: production
    command: bin/rails s -p 3000 -b 0.0.0.0
    environment:
      DATABASE_URL: postgresql://postgres@db/heimverwaltung_production
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      APP_HOST: ${APP_HOST}
      MAILER_URL: ${MAILER_URL}
      RAILS_SERVE_STATIC_FILES: 'true'
      MEMCACHE_SERVERS: memcached
    depends_on:
      - db

  memcached:
    image: memcached:1.5-alpine
    command: [ memcached, -l, '0.0.0.0', -p, '11211' ]

volumes:
  db_data:
