version: '3.5'
services:

  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - app_bundle:/usr/local/bundle/
    ports:
      - '3000:3000'
    entrypoint: [".docker/entrypoints/app.sh"]
    command: ["bin/rails", "s", "-b", "0.0.0.0", "-p", "3000"]
    environment:
      DATABASE_URL: postgresql://postgres@db/heimverwaltung_development
      # DATABASE_URL: postgresql://postgres@db/heimverwaltung_production
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpack
      MAILER_URL: "smtp://mail?from=no-reply@heimverwaltung.localhost"
    depends_on:
      - db
      - webpack
      - mail
    tty: true
    stdin_open: true

  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: heimverwaltung_test

  webpack:
    build:
      context: .
      target: development
    entrypoint: [".docker/entrypoints/webpack.sh"]
    command: ["bin/webpack-dev-server"]
    entrypoint: ./.docker/entrypoints/webpack.sh
    volumes:
      - .:/app
      - webpack_node_modules:/app/node_modules
      - webpack_bundle:/usr/local/bundle/
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - '3035:3035'

  mail:
    image: tophfr/mailcatcher
    ports:
      - '1080:80'
      - '1025:25'

  memcached:
    image: memcached:1.5-alpine
    command: [ memcached, -l, '0.0.0.0', -p, '11211' ]

  test:
    build:
      context: .
      target: development
    entrypoint: [".docker/entrypoints/app.sh"]
    command: ["bin/check"]
    volumes:
      - .:/app
      - test_node_modules:/app/node_modules
      - test_bundle:/usr/local/bundle/
    environment:
      E2E_HOST: 'http://production:3002'
      RAILS_PORT: 3002
      DATABASE_URL: postgresql://postgres@db/heimverwaltung_test
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 'true'
      RAILS_ENV: test
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
      MAILER_URL: "test://localhost?from=no-reply@heimverwaltung.localhost"
    depends_on:
      - db
      - selenium
    networks:
      default:
      selenium:

  production:
    build: .
    image: heimv:latest
    ports:
      - '3002:3002'
    volumes:
      - app_bundle:/usr/local/bundle/
    environment:
      DATABASE_URL: postgresql://postgres@db/heimverwaltung_test
      MAILER_URL: "smtp://mail?from=no-reply@heimverwaltung.localhost"
      SECRET_KEY_BASE: 'test'
      RAILS_SERVE_STATIC_FILES: 'true'
      PORT: 3002
      LOG_LEVEL: 'debug'
      #MEMCACHE_SERVERS: memcached
      RUBYOPT: '-W:no-deprecated -W:no-experimental'
    depends_on:
      - db
      - mail
      #- memcached
    networks:
      default:
      selenium:

  selenium:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    networks:
      selenium:

networks:
  selenium:

volumes:
  test_bundle:
  app_bundle:
  bundle_cache:
  node_modules:
  test_node_modules:
  webpack_bundle:
  webpack_node_modules:
  db_data:
