version: '3.5'
services:

  app:
    build:
      context: .
      target: production
    environment:
      DATABASE_URL: postgresql://postgres@db/heimverwaltung_production
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      APP_HOST: ${APP_HOST}
      MAILER_URL: ${MAILER_URL}
      MEMCACHE_SERVERS: memcached
    depends_on:
      - db
      - memcached

  memcached:
    image: memcached:1.5-alpine
    command: [ memcached, -l, '0.0.0.0', -p, '11211' ]