name: Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build :latest
      if: success()
      run: docker-compose -f docker-compose.yml -f docker-compose.e2e.yml build --no-cache e2e_target e2e_test
      env:
        UID: 0
        GID: 0

    - name: Run e2e
      if: success()
      run:
        - docker-compose -f docker-compose.yml -f docker-compose.e2e.yml run e2e_target bin/rails db:create db:migrate
        - docker-compose -f docker-compose.yml -f docker-compose.e2e.yml run e2e_test bin/check
        - docker-compose -f docker-compose.yml -f docker-compose.e2e.yml run e2e_test bin/e2e

    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_REGISTRY_URL: docker.pkg.github.com

    - name: Tag image
      if: success()
      run: docker tag heimv:latest docker.pkg.github.com/diegosteiner/heimverwaltung/heimv:${GITHUB_REF##*/}

    - name: Push to docker hub :latest
      if: success()
      uses: actions-hub/docker@master
      with:
        args: push docker.pkg.github.com/diegosteiner/heimverwaltung/heimv:${GITHUB_REF##*/}
