name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    # - uses: actions/cache@master
    #   with:
    #     path: vendor
    #     key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-gems-

    # - uses: actions/cache@master
    #   with:
    #     path: node_modules
    #     key: ${{ runner.os }}-npm-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-npm-${{ env.cache-name }}-
    #       ${{ runner.os }}-npm-
            
    - run: mkdir -p vendor/cache node_modules

    - name: Build test container
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml build e2e_test
      env:
        UID: 0
        GID: 0

    - name: Run check
      if: success()
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run e2e_test bin/check

    - name: Build and start e2e
      if: success()
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d e2e_target
      env:
        UID: 0
        GID: 0

    - name: Prepare Database
      if: success()
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run e2e_target bin/rails db:create db:migrate

    - name: Run e2e
      if: success()
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run e2e_test bin/e2e

    - name: Save logs
      if: failure()
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml logs e2e_target > /tmp/e2e_target.log; sudo mv /tmp/e2e_target.log ./tmp/

    - name: Upload tmp
      uses: actions/upload-artifact@master
      if: failure()
      with:
        name: screenshots
        path: tmp/capybara

    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      if: success()
      env:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_REGISTRY_URL: docker.pkg.github.com

    - name: Tag image
      if: success()
      run: docker tag heimv:latest docker.pkg.github.com/diegosteiner/heimv/heimv:${GITHUB_REF##*/}

    - name: Push to docker hub :latest
      if: success()
      uses: actions-hub/docker@master
      with:
        args: push docker.pkg.github.com/diegosteiner/heimv/heimv:${GITHUB_REF##*/}
